# Generated by Django 4.1.2 on 2023-11-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_watchlist_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/listings'),
        ),
    ]
