# Generated by Django 4.1.2 on 2023-11-10 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchers',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(related_name='watchlistings', to=settings.AUTH_USER_MODEL),
        ),

        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
